### ISSUE TITLE
多个组件同时使用，rollFinish事件只能触发其中一个。

### ISSUE THREAD

**Issue by Nirodhiko** [gitWhatever/vue-digitroll#13]

**Comment by gitWhatever** [comment]
不是不维护了，处理得慢一些，如果有更好的当然也推荐使用。
最近提的问题我还是会抽空看看修复掉，保障这个组件尽量满足大家需求。

**Comment by shun89** [comment]
其实你做的滑动效果挺好的，只是bug真的有点多，我花了很长时间去尝试解决遇到的bug，想在项目里用这个组件，但最后只能放弃，我也没有修复bug的能力，只能跑路了。
