### ISSUE TITLE
dist 文件夹缺失导致无法 import

### ISSUE THREAD

**Issue by bq-hentai** [gitWhatever/vue-digitroll#4]
解决方案可以是：

1、.gitignore 移除 dist/ 或者 package.json 中 files 加上
2、修改 package.json 中的 main 字段，直接映射到 `src/component/` 中的组件

建议直接删除 .gitignore 中的 dist

**Comment by bq-hentai** [comment]
https://github.com/gitWhatever/vue-digitroll/pull/5

**Comment by gitWhatever** [comment]
抱歉，package.json中的main的指向写的有问题，这里应该指向"lib/index.js"。但是 .gitignore 上无需去掉dist，因为github上只是存放代码的地方，本质不应该存放生成的产物(之后我会把仓库上的dist去掉)。真正输出产物的是npm，所以每次publish前执行打包，生成main文件指向的输出产物即可，之前无法 import，是因为main的指向写的有问题，非常抱歉~

**Comment by gitWhatever** [comment]
抱歉，package.json中的main的指向写的有问题，这里应该指向"lib/index.js"。但是 .gitignore 上无需去掉dist，因为github上只是存放代码的地方，本质不应该存放生成的产物(之后我会把仓库上的dist去掉)。真正输出产物的是npm，所以每次publish前执行打包，生成main文件指向的输出产物即可，之前无法 import，是因为main的指向写的有问题，非常抱歉~

**Comment by gitWhatever** [comment]
现在npm包更新到最新版本可正常使用了。  最新版本为：@huoyu/vue-digitroll@1.0.3

**Comment by bq-hentai** [comment]
fixed via https://github.com/gitWhatever/vue-digitroll/commit/1d6ccf4ffc7faf773b0e56eab7f94563722699ee
